0pdd fix due to min-word restriction
ERROR: Puzzle upgrades/sqlite/001-install-main-lazylead-tables.sql:32-32 has a very short description of just 8 words while a minimum of 10 is required
ERROR: Puzzle upgrades/sqlite/001-install-main-lazylead-tables.sql:49-49 has a very short description of just 8 words while a minimum of 10 is required
ERROR: Puzzle upgrades/sqlite/001-install-main-lazylead-tables.sql:56-56 has a very short description of just 8 words while a minimum of 10 is required
ERROR: Puzzle .docker/docker-compose.yml:3-3 has a very short description of just 3 words while a minimum of 10 is required
ERROR: Puzzle lib/lazylead/cli/start.rb:40-40 has a very short description of just 9 words while a minimum of 10 is required
ERROR: 5 errors, see log above